# Generated by Django 5.2 on 2025-04-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("almoxarifado", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="perfil",
            new_name="categoria",
        ),
    ]
