# Generated by Django 5.2 on 2025-04-07 23:57

import almoxarifado.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almoxarifado", "0003_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="registrado_por",
        ),
        migrations.AddField(
            model_name="item",
            name="codigo",
            field=models.CharField(default="SEMCOD", max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="item",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="criado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="quantidade",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FotoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to=almoxarifado.models.caminho_imagem_item
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="almoxarifado.item",
                    ),
                ),
            ],
        ),
    ]
