# Generated by Django 5.2 on 2025-04-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almoxarifado", "0004_remove_item_registrado_por_item_codigo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoitem",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fotoitem",
            name="imagem",
            field=models.ImageField(upload_to="itens/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="codigo",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
    ]
