# Generated by Django 5.2 on 2025-04-09 22:55

import almoxarifado.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "almoxarifado",
            "0005_alter_fotoitem_descricao_alter_fotoitem_imagem_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoitem",
            name="imagem",
            field=models.ImageField(upload_to=almoxarifado.models.caminho_imagem_item),
        ),
        migrations.AlterField(
            model_name="item",
            name="criado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_cadastrados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
