# Generated by Django 5.2 on 2025-04-10 00:26

import almoxarifado.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almoxarifado", "0006_alter_fotoitem_imagem_alter_item_criado_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoitem",
            name="imagem",
            field=models.ImageField(upload_to=almoxarifado.models.caminho_imagem_item),
        ),
    ]
