# Generated by Django 5.2 on 2025-04-10 22:37

import almoxarifado.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almoxarifado", "0007_alter_fotoitem_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.TextField()),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="VisualizacaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name="fotoitem",
            name="imagem",
            field=models.ImageField(upload_to=almoxarifado.models.caminho_imagem_item),
        ),
        migrations.AlterField(
            model_name="item",
            name="quantidade",
            field=models.FloatField(default=0),
        ),
    ]
