# Generated by Django 5.2 on 2025-04-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "almoxarifado",
            "0008_logsistema_visualizacaosistema_alter_fotoitem_imagem_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Usuário", "verbose_name_plural": "Usuários"},
        ),
        migrations.AlterModelOptions(
            name="fotoitem",
            options={
                "verbose_name": "Foto do Item",
                "verbose_name_plural": "Fotos dos Itens",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["codigo"],
                "verbose_name": "Item",
                "verbose_name_plural": "Itens",
            },
        ),
        migrations.AlterModelOptions(
            name="logsistema",
            options={
                "ordering": ["-data"],
                "verbose_name": "Log do Sistema",
                "verbose_name_plural": "Logs do Sistema",
            },
        ),
        migrations.AlterModelOptions(
            name="visualizacaosistema",
            options={
                "verbose_name": "Visualização do Sistema",
                "verbose_name_plural": "Visualizações do Sistema",
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="codigo",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
