# Generated by Django 5.2 on 2025-04-10 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "almoxarifado",
            "0009_alter_customuser_options_alter_fotoitem_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logsistema",
            options={},
        ),
        migrations.AddField(
            model_name="logsistema",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs_realizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
